### ISSUE TITLE
[Bug] destination schema

### ISSUE THREAD

**Issue by raphaelvarieras** [fivetran/dbt_zuora_source#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

I am not able to define the destinations schema for the staging models of this source the same way as other Fivetran packages. This is likely due to an issue in the package's `dbt_project.yml` file.

### Relevant error log or model output

The model config doesn't match the package name:

```shell
models:
  dbt_zuora_source:
    +schema: zuora_source
    materialized: table
    tmp:
      materialized: view
```

### Expected behavior

See example of other Fivetran source packages like `github_source`:
```
models:
  github_source:
    materialized: table
    tmp:
      materialized: view
```

Or `apple_store_source`:
```
models:
  apple_store_source:
    materialized: table
    +schema: apple_store_source
    tmp:
      materialized: view
```

### dbt Project configurations

N/A

### Package versions

  - package: fivetran/zuora_source # Needed temporarily until the Zuora package below catches up
    version: 0.1.2

### What database are you using dbt with?

snowflake

### dbt Version

1.5

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [ ] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.
